videogame1 = Videogame.create(name:"Sonic 06", release_year: 2019, description:"Blue dude runs around")
videogame2 = Videogame.create(name:"Cyberpunk 2077", release_year: 2037, description:"Punkguy")
videogame3 = Videogame.create(name:"Frogger", release_year: 2000, description:"Frog cross street, dies.")
videogame4 = Videogame.create(name:"Ratchet and Clank: A Crack in time", release_year: 2006, description:"Cat boy hangs out with smart robot")

Review.create(rating: 5, body: "Amy is my waifu, not enough Amy. Checkout out my deviantart", title: "not enough amy", videogame: videogame1)
Review.create(rating: 3, videogame: videogame1)
Review.create(rating: 4, body: "good stuff", videogame: videogame2)
Review.create(rating: 2, body: "FOLLOW ME ON INSTAGRAM @CHUBBYCHUB02", title: "FOLLOW BACK", videogame: videogame2)
Review.create(rating: 5, body: "Perfect game", title: "I love games", videogame: videogame3)
Review.create(rating: 3, body: "HAHAHAHAHAHAHAHA", title: "GREAT VIDEOGAME GUYS", videogame: videogame3)
Review.create(rating: 4, body: "noice", title: "noice", videogame: videogame3)
Review.create(rating: 4, title:"Cat boy?", body:"Catboy is kinda weird", videogame: videogame4)